Adding population variable on the Census Tract level
BasisResearch/cities pull request #124
Opened 2024-06-21 10:13 UTC by Niklewa

Adding a population variable and creating a source of truth for Census Tract variables.

2024-06-25 09:24 UTC, Niklewa commented
In this PR, I have downloaded Census API data about the population from 2010 to 2022. Given the complexity of Census tracts, the dataset was split into pre- and post-2020 periods, reflecting changes in Census tract definitions.

Additionally, a new `VariableCleanerCT` class and `CTDataGrabberCSV` were developed for use with this data level. I have also created tests to verify the data's accuracy.

Interestingly, a linting problem arises during Git checks, my linting does not indicate any necessary changes.

2024-06-25 15:30 UTC, Niklewa commented
I fixed the lint issue, I updated `black` library on my setup and it made the necessary changes.

2024-07-01 12:03 UTC, rfl-urbaniak requested changes
Do I understand correctly that the raw data import logic now lives only in a notebook which is called "clean_population_tracts"? 

If yes, this might make future updates hard, no one will rember what's what and user will be forced to browse through experimental notebooks to find the right chunks of code. 

Please extract the core of the data import code, put in a script, and place in new folder `cities/utils/scraping`.

Do I see correctly that you did data grabber for csv but for now did not do one for DB, postponing this work potentially for later?

2024-07-02 10:28 UTC, Niklewa commented on cities/utils/data_grabber.py
> -    check = df.columns[2:].isin(years_to_check).any().any()
I have changed that during some debugging, the first version seems to be better, as it omits two first columns.

2024-07-02 11:10 UTC, Niklewa commented on cities/utils/data_grabber.py
> +        self, level_DG: str = "pre_2020"
Instead I used `ct_time_period`

2024-07-02 11:13 UTC, Niklewa commented on cities/utils/data_grabber.py
> +            "Invalid level. Please choose 'county', 'census_tract' or 'msa'."
resolved with changing the name of `level_DG`

2024-07-03 16:19 UTC, rfl-urbaniak requested changes
two really small things left; also, the setup now contains the new dependency

2024-07-03 16:19 UTC, rfl-urbaniak commented on cities/utils/clean_variable.py
> +        year_or_category: str = "Year",
still, the name is confusing. Please change.:)

2024-07-03 16:19 UTC, rfl-urbaniak commented on cities/utils/data_grabber.py
> -    check = df.columns[2:].isin(years_to_check).any().any()
which version do you call the first version, the one that you deleted?

2024-07-04 07:58 UTC, Niklewa commented on cities/utils/data_grabber.py
> -    check = df.columns[2:].isin(years_to_check).any().any()
I returned to the original version, which I called the first version

2024-07-04 08:16 UTC, Niklewa commented on cities/utils/clean_variable.py
> +        year_or_category: str = "Year",
Changed to `year_or_category_column_label`

2024-07-04 11:16 UTC, rfl-urbaniak approved these changes

2024-07-04 11:16 UTC, merged