Adding income variable on a census tract level
BasisResearch/cities pull request #129
Opened 2024-07-09 12:07 UTC by Niklewa

2024-07-09 16:43 UTC, rfl-urbaniak approved these changes

2024-07-09 16:45 UTC, rfl-urbaniak requested changes
This branch has conflicts (probably arose after merging the previous data branch), most likely harmless. Please take a look and fix before merging.

2024-07-18 14:21 UTC, rfl-urbaniak requested changes
Guide has "Income distribution" for the previous income data and "income (census tract)" with no reference in TOC. Please clean up and rethink document structure and make sure the TOC makes sense and links work.

2024-07-25 10:20 UTC, Niklewa commented
> Guide has "Income distribution" for the previous income data and "income (census tract)" with no reference in TOC. Please clean up and rethink document structure and make sure the TOC makes sense and links work.

'Income distribution' and 'Income' are distinct variables. The former consists of several categories of income, while the latter refers to the mean and median income.

2024-08-02 17:25 UTC, merged